---
- name: Playbook to configure AAP
  hosts: localhost
  gather_facts: false
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    !
    !
    - name: Import role-aap-object-schedule
      ansible.builtin.include_role:
        name: role-aap-object-schedule
      vars:
        build: true
        schedule_name: "{{ item.value.schedule_name }}"
        job_template: "{{ item.value.job_template }}"
        rrule: "{{ item.value.rrule }}"
        description: "{{ common_description }}"
      loop: "{{ lookup('dict', schedules) }}"
    !
    !