---
# Create schedule
- name: "Build a schedule for {{ name }}"
  ansible.controller.schedule:
    name: "{{ schedule_name }}"
    state: present
    unified_job_template: "{{ job_template }}"
    rrule: "{{ rrule }}"
    description: "{{ description }}"
  register: result